# Generated by Django 5.1.6 on 2025-02-25 14:52

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, validators=[app.models.validator_email]),
        ),
    ]
